[postgresql]
# Если база на том же сервере, что и бот, оставь localhost
host=localhost
# Имя базы данных, которую ты создал в pgAdmin
database=Repair
# Имя пользователя PostgreSQL
user=имя
# Пароль от пользователя
password=пароль
# Стандартный порт PostgreSQL
port=5432
