[postgresql]
# Локальный сервер
host=localhost
# Имя базы данных
database=Repair
# Имя пользователя PostgreSQL
user=пользователь
# Пароль от пользователя
password=пароль
# Стандартный порт PostgreSQL
port=5432
